### ISSUE TITLE
Use binary data as HMAC key

### ISSUE THREAD

**Issue by tristan-k** [digintLab/yubikey-server#3]
Please see https://github.com/neverpanic/simpleid-yubikey/issues/1 and https://github.com/neverpanic/yubikey-server/commit/30abb089317a35be738f2af6a979e1a6ad88f6e8

**Comment by stumpyfr** [comment]
hmm, not my yubikey to test that.
Do you confirm the problem is solved with that patch? if you have time to make a PR, would be great or I will do it myself when back at home.

**Comment by neverpanic** [comment]
I'll work on a PR, it seems the error handling in my change could be improved as well.

**Comment by neverpanic** [comment]
Superseded by #4.

**Comment by stumpyfr** [comment]
merge #4
